apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: poke-go-friends-dev

resources:
  - ../../base

patches:
  - path: backend-patch.yaml
  - path: ingress-patch.yaml

replicas:
  - name: poke-go-backend
    count: 1
  - name: postgres
    count: 1
  - name: redis
    count: 1
