services:
  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=pokecodeshare
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - spring-postgres
  db:
    image: ghcr.io/mikemikerson/postgres:15-alpine
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=poke_go_friends
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
  redis:
    image: ghcr.io/mikemikerson/redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - spring-postgres
volumes:
  db-data:
  redis-data:
secrets:
  db-password:
    file: .env/db.txt
networks:
  spring-postgres: