apiVersion: apps/v1
kind: Deployment
metadata:
  name: poke-go-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poke-go-backend
  template:
    metadata:
      labels:
        app: poke-go-backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend
          image: ghcr.io/mikemikerson/poke-go-friends-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "jdbc:postgresql://postgres:5432/poke_go_friends"
            - name: DATABASE_USERNAME
              value: "postgres"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 240
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: poke-go-backend
spec:
  selector:
    app: poke-go-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
