apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: poke-go-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: poke-go.local
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: poke-go-backend
                port:
                  number: 8080
