apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: poke-go-friends-base

resources:
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - backend.yaml
  - ingress.yaml
  - cluster-issuer.yaml
