apiVersion: apps/v1
kind: Deployment
metadata:
  name: poke-go-backend
spec:
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: DATABASE_URL
          value: "jdbc:postgresql://postgres:5432/poke_go_friends"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
