apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: poke-go-friends-production

resources:
  - ../../base

namePrefix: prod-

patches:
  - path: backend-patch.yaml

replicas:
  - name: poke-go-backend
    count: 2
  - name: postgres
    count: 1
  - name: redis
    count: 1
